course:
  openapi:
    dev-url: http://localhost:8080
    prod-url: https://course-api.istad.co

spring:
  application:
    name: course
  data:
    mongodb:
      uri: mongodb://rathana:rathana%10@localhost:27020/
      database: homework_course
#      authentication-database: admin
server:
  tomcat:
    relaxed-query-chars: >
      |,[,],{,}
  forward-headers-strategy: framework
stream:
  image: http://localhost:8080/image/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      uri: mongodb://rathana:rathana%10@homework-course:27017/